export const config = {
  // BASEURL: "http://localhost:3000/v1/",
  BASEURL: "http://46.202.164.175:3000/v1/",
  MainUrl: "http://46.202.164.175:3000/",
  // MainUrl: "http://localhost:3000/v1/",

  USERLOGIN: "admin/auth/login",
  SIGNUP: "admin/auth/signup",
  VERFICATION: "admin/auth/forgot-password",
  VERIFY_CODE: "admin/auth/reset-password",
  SetNewPassword: "admin/auth/set-new-password",
  ChangeNewPassword: "admin/auth/change-password",
  logout: "admin/auth/logout",
  LIST_CATEGORIES: "admin/category/list",
  CREATE_CATEGORY: "admin/category/create",
  DELETE_CATEGORY: "admin/category",
  UPDATE_CATEGORY: "admin/category",
  GET_CATEGORY_DETAILS: "admin/category",
  ADD_CLASS: "admin/category",
  UPDATE_CLASS: "admin/category",
  DELETE_CLASS: "admin/category",
  GET_CLASS_DETAILS: "admin/class",
  CREATE_SUBJECT: "admin/class",
  UPDATE_SUBJECT: "admin/class/",

  SUBSCRIBED_USERS: "admin/dashboard/subscribed-users",
  SUBSCRIPTION_STATS: "admin/dashboard/subscription-stats",
  DASHBOARD_USERS: "admin/dashboard/users",
  SUBSCRIPTION_WORKFLOW: "admin/dashboard/subscription-workflow",
  ADD_SUBSCRIPTION: "admin/dashboard/add-subscription-to-user",
  AVAILABLE_SUBSCRIPTIONS: "admin/dashboard/available-subscriptions",
  GET_AVAILABLE_SUBSCRIPTIONS: "admin/dashboard/available-subscriptions",
  RESELLER_LIST: "admin/resellers",

  CREATE_ASSESSMENT: "/assessment/create-assessment/",
  GET_ASSESSMENT: "/assessment/get-assessment/",
  GET_PAYMENTS: "admin/payments",
  GET_PAYMENTS_DETAILS: "admin/payments",
  GET_UNIVERSITY: "admin-universities/list",
  ADD_UNIVERSITY: "admin-universities/add",
  UPDATE_UNIVERSITY: "admin-universities",
  DELETE_UNIVERSITY: "admin-universities",

  GET_TEACHERS: "admin_teacher/list",

  // logout: "admin/auth/logout",
  RESET_PASSWORD: "auth/reset-password",
  GET_DASHBOARD: "admin/users/get-dashboard-details",
  GET_COURSES: "utils/get-admin-courses",

  USER: "admin/users/get-statistics",
  GETUSER: "admin/users/get-users",
  GET_USER_BY_ID: "get-user-by-id",
  UPLOAD_USERS: "admin/users/upload-bulk-user",
  UPDATE_USER: "admin/users/update-user",
  ADDUSER: "admin/users/add-user",
  GETUSERSCSV: "admin/users/get-users-csv",
  GETUSERSFEEDBACK: "admin/users/get-user-feedbacks",
  GETUSERFEEDBACK: "admin/users/get-user-feedback",
  REPLYFEEDBACK: "admin/users/reply-to-feedback",
  GET_LEADERBOARD: "leaderBoard/get-leaderboard",
  GET_LOCAL_SCHOOLS: "leaderBoard/get-local-schools",
  GET_USER_PROFILE: "leaderboard/get-user-profile",
  GET_PERFORMANCE_HISTORY: "leaderboard/get-performance-history",
  GET_MONTHLY_POINTS: "leaderboard/get-monthly-points",
  GET_ADMIN_ROLES: "admin/users/get-admin-roles",
  GET_ADMIN_ROLE_PERMISSION: "admin/users/get-admin-role-permission",
  UPDATE_ROLE_PERMISSION: "admin/users/update-role-permission",
  ADD_ADMIN_USER: "admin/users/add-admin-user",
  GET_ADMIN_USERS: "admin/users/get-admin-users",
  GET_ADMIN_USER: "admin/users/get-admin-user",
  // GET_TEACHERS: "admin/teachers/get-teachers",
  GET_TEACHER_STATISTICS: "admin/teachers/get-statistics",
  // ADD_TEACHER: "admin/teachers/add-teacher",
  ADD_TEACHER: "admin_teacher/create",
  UPDATE_TEACHER: "admin/teachers/update-teacher",
  GET_TEACHER_DETAILS: "admin/live-classes/get-teacher-live-class",
  GET_LOCAL_GOV: "admin/users/get-local-government",
  CHANGE_PASSWORD: "auth/change-password",
  ADD_LIVE_CLASS: "live/create-live-class",
  UPDATE_LIVE_CLASS: "admin/live-classes/update-live-class",
  DELETE_LIVE_CLASS: "live/delete-live-class",
  GET_LIVE_CLASSSES: "live/live-classes-admin",
  GET_LIVE_CLASS: "admin/live-classes/get-live-class",
  GET_USER_FEEDBACKS_CSV: "admin/users/get-user-feedbacks-csv",
  GET_LIVE_CLASS_TEACHERS: "admin/teachers/get-live-class-teachers",
  RESERVE_LIVE_CLASS: "live-classes/reserve-live-class",
  GET_STUDENTS_LIVE_CLASS: "admin/live-classes/get-students-live-class",
  DELETE_USER: "admin/users/delete-user",

  GET_TOTAL_SUBSCRIBERS: "admin/users/get-total-subscribers",
};
