export const config = {
  BASEURL: 
  //"https://29f3-182-68-25-240.ngrok-free.app/v1/",
   "https://api.v2.teesas.com/v1/",
   GET_DASHBOARD:"admin/users/get-dashboard-details",
   GET_COURSES:"admin/live-classes/get-course-details",
  USERLOGIN: "auth/admin-login",
  VERFICATION: "auth/send-verification-code",
  VERIFY_CODE:"auth/verify-code",
  RESET_PASSWORD:"auth/reset-password",
  USER: "admin/users/get-statistics",
  GETUSER: "admin/users/get-users",
  GET_USER_BY_ID:"get-user-by-id",
  UPLOAD_USERS:"admin/users/upload-bulk-user",
  UPDATE_USER:"admin/users/update-user",
  ADDUSER: "admin/users/add-user",
  GETUSERSCSV:"admin/users/get-users-csv",
  GETUSERSFEEDBACK:"admin/users/get-user-feedbacks",
  GETUSERFEEDBACK:"admin/users/get-user-feedback",
  REPLYFEEDBACK:"admin/users/reply-to-feedback",
  GET_LEADERBOARD: 'leaderBoard/get-leaderboard',
  GET_LOCAL_SCHOOLS: 'leaderBoard/get-local-schools',
  GET_USER_PROFILE: 'leaderboard/get-user-profile',
  GET_PERFORMANCE_HISTORY: 'leaderboard/get-performance-history',
  GET_MONTHLY_POINTS: 'leaderboard/get-monthly-points',
  GET_ADMIN_ROLES:"admin/users/get-admin-roles",
  GET_ADMIN_ROLE_PERMISSION:"admin/users/get-admin-role-permission",
  UPDATE_ROLE_PERMISSION:"admin/users/update-role-permission",
  ADD_ADMIN_USER:"admin/users/add-admin-user",
  GET_ADMIN_USERS:"admin/users/get-admin-users",
  GET_ADMIN_USER:"admin/users/get-admin-user",
  GET_TEACHERS:"admin/teachers/get-teachers",
  GET_TEACHER_STATISTICS:"admin/teachers/get-statistics",
  ADD_TEACHER:"admin/teachers/add-teacher",
  UPDATE_TEACHER:"admin/teachers/update-teacher",
  GET_TEACHER_DETAILS:"admin/live-classes/get-teacher-live-class",
  GET_LOCAL_GOV:"admin/users/get-local-government",
  CHANGE_PASSWORD:"auth/change-password",
  ADD_LIVE_CLASS:"admin/live-classes/add-live-class",
  UPDATE_LIVE_CLASS:"admin/live-classes/update-live-class",
  DELETE_LIVE_CLASS:"admin/live-classes/delete-live-class",
  GET_LIVE_CLASSSES:"admin/live-classes/get-live-classes",
  GET_LIVE_CLASS:"admin/live-classes/get-live-class",
  GET_USER_FEEDBACKS_CSV:"admin/users/get-user-feedbacks-csv",
  GET_LIVE_CLASS_TEACHERS:"admin/teachers/get-live-class-teachers",
  RESERVE_LIVE_CLASS:"live-classes/reserve-live-class",
  GET_STUDENTS_LIVE_CLASS:"admin/live-classes/get-students-live-class",
  DELETE_USER:"admin/users/delete-user",

  GET_TOTAL_SUBSCRIBERS: "admin/users/get-total-subscribers",

};
