name: Development pipeline

on:
  push:
# I changed the branch from develop to production
    branches:
      - production
env:
  REPO_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          yarn install
      - name: Build Project
        run: |
          yarn build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Migrations via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/html/teesas-new-infra/teesas_admin
            echo "hello world ++++" >> testing123
            # sudo git config --global --add safe.directory /***/teesas_admin
            # git fetch --all
            # git reset --hard origin/develop
            # rm -rf package-lock.json
            # rm -rf node_modules
            # npm install
            # yarn build
            # pm2 restart teesas_admin
            # pm2 save
  notify-teams:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: always()
    steps:
      - name: Set Color and Message for Success
        if: ${{ needs.build.result == 'success' && needs.deploy.result == 'success' }}
        run: |
          echo "COLOR=success" >> $GITHUB_ENV
          echo "MESSAGE=✅ Pipeline succeeded for repository $REPO_NAME!" >> $GITHUB_ENV
      - name: Set Color and Message for Failure
        if: ${{ needs.build.result != 'success' || needs.deploy.result != 'success' }}
        run: |
          echo "COLOR=failure" >> $GITHUB_ENV
          echo "MESSAGE=❌ Pipeline failed for repository $REPO_NAME!" >> $GITHUB_ENV
      - name: Send Notification to Teams
        uses: mikesprague/teams-incoming-webhook-action@v1.13.5
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: "Pipeline Notification for ${{ env.REPO_NAME }}"
          message: ${{ env.MESSAGE }}
          deploy-card: true
          color: ${{ env.COLOR }}
